import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@components/nav-bar";
import classnames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classnames(inter.className, "bg-illustration p-8")}>
        <NavBar />
        <main className="mx-auto max-w-5xl rounded-b-[30px] rounded-tl-[30px] bg-light-background">
          {children}
        </main>
      </body>
    </html>
  );
}
