import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@components/nav-bar";
import illustrationImg from "@assets/images/illustration.jpg";
import classnames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

console.log(illustrationImg);
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classnames(inter.className, "p-8")}>
        <NavBar></NavBar>
        <main>{children}</main>
      </body>
    </html>
  );
}
